on:
  push:
    tags:
      - 'v*.*.*'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
    publish:
        environment: publish
        runs-on: macos-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-java@v4
            with:
              distribution: 'zulu'
              java-version: 21

          - uses: gradle/actions/setup-gradle@v4
          - run: ./gradlew publish --no-configuration-cache --continue
            env:
              ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USER }}
              ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
              ORG_GRADLE_PROJECT_signingInMemoryKey: ${{secrets.MAVEN_GPG_SECRET_KEY}}
              ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{secrets.MAVEN_GPG_SERCRET_PASSWORD}}
              GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
              GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}